services:
  email_sender_postgres:
    image: postgres
    container_name: email_sender_postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
